# -*- coding: utf-8 -*-
"""API_CEP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x4hiFtjv8eSvm-eKW3L0zSS-ji5ke0I1
"""

# https://viacep.com.br

# viacep.com.br/ws/01001000/json/  # JSON Format
# viacep.com.br/ws/01001000/xml/  # XML Format

import requests

x = requests.get('https://viacep.com.br/ws/01001000/json/')
print(x.text)
print(type(x.text))

import json

s = x.text
json_acceptable_string = s.replace("'", "\"")
d = json.loads(json_acceptable_string)

print(type(d))
d

import requests

x = requests.get('https://viacep.com.br/ws/01001000/xml/')
print(x.text)

!pip install kora -q

from kora.selenium import wd
from IPython.display import clear_output

wd.get('http://viacep.com.br/ws/01001000/json/')
wd.page_source
clear_output()

display(wd)

